import { styled } from "@mui/material/styles";
import Button, { ButtonProps } from "@mui/material/Button";

export const FooterShell = styled("footer")(({ theme }) => ({
  width: "100%",
  margin: 0,
  boxSizing: "border-box",
  paddingTop: 20,
  paddingBottom: 20,
  isolation: "isolate",
  [theme.breakpoints.down("md")]: {
    paddingTop: 20,
    paddingBottom: 20,
  },
  [theme.breakpoints.down("sm")]: {
    paddingTop: 20,
    paddingBottom: 20,
  },
}));

export const FooterBG = styled("div")(({ theme }) => ({
  width: "min(1400px, calc(100% - 40px))",
  height: 800,
  position: "relative",
  margin: "0 auto",
  paddingLeft: 50,
  paddingRight: 50,
  borderRadius: 30,
  overflow: "hidden",
  backgroundImage: `
    linear-gradient(180deg,
      rgba(14,27,65,0) 0%,
      rgba(14,27,65,0.86) 64%,
      rgba(14,27,65,1) 84%
    ),
    radial-gradient(1200px 500px at 20% 92%,
      rgba(0,133,255,0.45) 0%,
      rgba(0,133,255,0) 60%
    ),
    url('/Background/BackgroundImage.jpg')
  `,
  backgroundBlendMode: "normal, multiply",
  backgroundSize: "cover, cover",
  backgroundRepeat: "no-repeat, no-repeat",
  backgroundPosition: "center top, center top",
  boxSizing: "border-box",
  display: "grid",
  justifyItems: "center",
  rowGap: 18,
  [theme.breakpoints.between("md", "lg")]: {
    minHeight: 760,
    paddingLeft: 40,
    paddingRight: 40,
    borderRadius: 30,
    rowGap: 18,
    backgroundPosition: "center top",
    backgroundSize: "cover",
    overflowX: "hidden",
    position: "relative",
    height: "auto",
  },
  [theme.breakpoints.down("md")]: {
    width: "calc(100% - 40px)",
    maxWidth: "100%",
    minHeight: 760,
    paddingLeft: 32,
    paddingRight: 32,
    borderRadius: 24,
    rowGap: 15,
    backgroundPosition: "center top",
    backgroundSize: "cover",
    overflowX: "hidden",
    position: "relative",
    height: "auto",
  },
  [theme.breakpoints.down("sm")]: {
    width: "calc(100% - 10px)",
    maxWidth: "100%",
    minHeight: 738,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 20,
    rowGap: 15,
    backgroundPosition: "center top",
    backgroundSize: "cover",
    overflowX: "hidden",
  },
}));

export const FooterTitle = styled("h2")(({ theme }) => ({
  margin: 0,
  marginTop: 80,
  width: 844,
  maxWidth: "100%",
  textAlign: "center",
  fontFamily: "var(--font-cg)",
  fontWeight: 600,
  fontSize: 46,
  lineHeight: "55px",
  color: "#0E1B41",
  [theme.breakpoints.down("md")]: {
    marginTop: 45,
    width: 550,
    fontSize: 28,
    lineHeight: "40px",
    textAlign: "center",
    marginLeft: 0,
  },
  [theme.breakpoints.down("sm")]: {
    marginTop: 45,
    width: 350,
    fontWeight: 600,
    fontSize: 28,
    lineHeight: "36px",
    textAlign: "center",
    color: "#0E1B41",
  },
}));

export const FooterLead = styled("p")(({ theme }) => ({
  margin: 0,
  width: 1000,
  marginTop: -200,
  maxWidth: "100%",
  textAlign: "center",
  fontFamily: "var(--font-crimson)",
  fontWeight: 400,
  fontSize: 24,
  lineHeight: "32px",
  color: "#F3F4F6",
  [theme.breakpoints.between("md", "lg")]: {
    width: 800,
    marginTop: 12,
    fontSize: 22,
    lineHeight: "30px",
  },
  [theme.breakpoints.down("md")]: {
    width: 550,
    marginTop: -10,
    fontSize: 16,
    lineHeight: "24px",
    textAlign: "center",
    marginLeft: 0,
  },
  [theme.breakpoints.down("sm")]: {
    width: 350,
    marginTop: -10,
    fontSize: 16,
    lineHeight: "24px",
    textAlign: "center",
    color: "#F3F4F6",
  },
}));

export const FooterCallBtn = styled(Button)<ButtonProps>(({ theme }) => ({
  width: 190,
  height: 55,
  borderRadius: 12,
  marginTop: -330,
  textTransform: "none",
  paddingTop: 18,
  paddingRight: 30,
  paddingBottom: 18,
  paddingLeft: 30,
  fontFamily: "var(--font-crimson)",
  fontWeight: 500,
  fontSize: 18,
  letterSpacing: "0.02em",
  color: "#FFFFFF",
  background: "linear-gradient(90deg, #0064B5 0%, #00A9DF 100%)",
  boxShadow: "0 1px 2px rgba(0,0,0,0.20)",
  "&:hover": {
    background: "linear-gradient(90deg, #005fa8 0%, #0098cf 100%)",
  },
  [theme.breakpoints.between("md", "lg")]: {
    marginTop: 20,
  },
  [theme.breakpoints.between("sm", "md")]: {
    marginTop: 10,
    width: 150,
    marginLeft: 0,
    height: 44,
    borderRadius: 10,
    padding: "8px 18px",
    fontSize: 15,
    lineHeight: "13px",
  },
  [theme.breakpoints.down("sm")]: {
    marginTop: 10,
    width: 110,
    height: 36,
    borderRadius: 10,
    padding: 0,
    fontSize: 14,
    lineHeight: "13px",
    textTransform: "none",
  },
}));

export const FooterAboutWrap = styled("div")(({ theme }) => ({
  position: "absolute",
  left: 50,
  bottom: 125,
  width: 500,
  height: "auto",
  display: "grid",
  rowGap: 15,
  padding: 0,
  boxSizing: "border-box",
  [theme.breakpoints.between("md", "lg")]: {
    position: "static",
    width: "100%",
    maxWidth: 900,
    rowGap: 12,
    justifyItems: "flex-start",
    alignItems: "start",
    textAlign: "left",
    marginLeft: 0,
    padding: 0,
  },
  [theme.breakpoints.down("md")]: {
    position: "static",
    width: "100%",
    maxWidth: 550,
    rowGap: 10,
    justifyItems: "center",
    alignItems: "start",
    textAlign: "center",
    marginLeft: 0,
    padding: 0,
  },
  [theme.breakpoints.down("sm")]: {
    position: "static",
    width: "100%",
    maxWidth: 375,
    rowGap: 10,
    justifyItems: "center",
    alignItems: "start",
    textAlign: "center",
    padding: 0,
  },
}));

export const FooterAboutTitle = styled("h3")(({ theme }) => ({
  margin: 0,
  width: 418,
  textAlign: "left",
  fontFamily: "var(--font-cg)",
  fontWeight: 600,
  fontSize: 32,
  lineHeight: "38px",
  color: "#FFFFFF",
  [theme.breakpoints.down("md")]: {
    width: "100%",
    maxWidth: 550,
    marginTop: 30,
    textAlign: "center",
    fontSize: 24,
    lineHeight: "30px",
    color: "#F3F4F6",
  },
  [theme.breakpoints.down("sm")]: {
    width: 350,
    marginTop: 30,
    textAlign: "center",
    fontWeight: 600,
    fontSize: 22,
    lineHeight: "100%",
    color: "#F3F4F6",
  },
}));

export const FooterAboutText = styled("p")(({ theme }) => ({
  margin: 0,
  width: 500,
  fontFamily: "var(--font-crimson)",
  fontWeight: 400,
  fontSize: 16,
  lineHeight: "24px",
  color: "#FFFFFF",
  [theme.breakpoints.down("md")]: {
    width: "100%",
    maxWidth: 550,
    fontSize: 14,
    lineHeight: "22px",
    textAlign: "center",
  },
  [theme.breakpoints.down("sm")]: {
    width: 350,
    fontSize: 12,
    lineHeight: "16px",
    textAlign: "center",
    color: "#FFFFFF",
  },
}));

export const FooterAboutDivider = styled("div")(({ theme }) => ({
  width: "100%",
  height: 1,
  background: "rgba(255,255,255,0.5)",
  [theme.breakpoints.down("md")]: {
    width: "100%",
    maxWidth: 550,
    margin: "6px 0 10px",
  },
  [theme.breakpoints.down("sm")]: {
    width: 350,
    margin: "6px 0 10px",
  },
}));

export const FooterSocialRow = styled("div")(({ theme }) => ({
  display: "grid",
  gridAutoFlow: "column",
  gap: 16,
  width: "max-content",
  height: 32,
  alignItems: "center",
  [theme.breakpoints.down("md")]: {
    gap: 15,
    width: "auto",
    height: 32,
    justifyContent: "center",
  },
  [theme.breakpoints.down("sm")]: {
    gap: 15,
    width: "auto",
    height: 32,
    justifyContent: "center",
  },
}));

export const SocialChip = styled("a")({
  width: 32,
  height: 32,
  borderRadius: 32,
  backgroundColor: "rgba(255,255,255,0.5)",
  border: "1px solid rgba(255,255,255,0.35)",
  backdropFilter: "blur(2px) saturate(130%)",
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  textDecoration: "none",
  transition:
    "transform .15s ease, background .15s ease, border-color .15s ease",
  "& .MuiSvgIcon-root": {
    fontSize: 18,
    color: "#FFFFFF !important",
    fill: "#FFFFFF",
    transform: "translateY(0.5px)",
  },

  "&:hover": {
    background: "linear-gradient(90deg, #0064B5 0%, #00A9DF 100%)",
    borderColor: "rgba(14,27,65,1)",
    transform: "translateY(-1px)",
  },

  "&.fb .MuiSvgIcon-root, &.li .MuiSvgIcon-root": {
    fontSize: 20,
    transform: "translateY(0.5px)",
  },
});

export const FooterInfoGrid = styled("div")(({ theme }) => ({
  position: "absolute",
  right: 50,
  bottom: 125,
  width: 550,
  height: 215,
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  columnGap: 30,
  rowGap: 10,
  [theme.breakpoints.between("md", "lg")]: {
    position: "static",
    right: "auto",
    bottom: "auto",
    width: "100%",
    maxWidth: 900,
    height: "auto",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    columnGap: 40,
    rowGap: 20,
    justifyItems: "start",
    alignItems: "start",
    margin: "20px auto 0",
    "& > div": {
      width: "100%",
      maxWidth: "100%",
      textAlign: "left",
      margin: 0,
    },
  },
  [theme.breakpoints.down("md")]: {
    position: "static",
    width: "100%",
    maxWidth: 550,
    height: "auto",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    columnGap: 25,
    rowGap: 20,
    justifyItems: "start",
    alignItems: "start",
    margin: "10px auto 0",

    "& > div:nth-of-type(1)": { order: 1, marginLeft: 30 },
    "& > div:nth-of-type(3)": {
      order: 2,
      marginTop: -4,
      marginBottom: 20,
      marginLeft: 50,
    },
    "& > div:nth-of-type(2)": { order: 3, marginLeft: 30 },
    "& > div:nth-of-type(4)": { order: 4, marginTop: -4, marginLeft: 50 },

    "& > div": { width: "100%", maxWidth: 220, textAlign: "left" },
  },
  [theme.breakpoints.down("sm")]: {
    position: "static",
    width: "100%",
    maxWidth: 375,
    height: "auto",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    columnGap: 25,
    rowGap: 20,
    justifyItems: "start",
    alignItems: "start",
    margin: "10px auto 0",

    "& > div:nth-of-type(1)": { order: 1 },
    "& > div:nth-of-type(3)": {
      order: 2,
      marginTop: -5,
      marginBottom: 20,
      marginLeft: 50,
    },
    "& > div:nth-of-type(2)": { order: 3 },
    "& > div:nth-of-type(4)": { order: 4, marginTop: 0, marginLeft: 50 },

    "& > div": { width: "100%", maxWidth: 17, textAlign: "left" },
  },
}));

export const InfoCol = styled("div")(({ theme }) => ({
  display: "grid",
  rowGap: 8,
  [theme.breakpoints.down("md")]: {
    rowGap: 6,
    width: 220,
  },
  [theme.breakpoints.down("sm")]: {
    rowGap: 6,
    width: 175,
  },
}));

export const InfoTitle = styled("div")(({ theme }) => ({
  fontFamily: "var(--font-cg)",
  fontWeight: 700,
  marginTop: 30,
  fontSize: 16,
  lineHeight: "19px",
  color: "#F3F4F6",
  [theme.breakpoints.between("sm", "md")]: {
    marginTop: 0,
    width: 100,
    fontWeight: 700,
    fontSize: 12,
    lineHeight: "100%",
  },

  [theme.breakpoints.down("sm")]: {
    marginTop: 0,
    width: 100,
    fontWeight: 700,
    fontSize: 11,
    lineHeight: "100%",
    color: "#F3F4F6",
  },
}));

export const InfosTitle = styled("div")(({ theme }) => ({
  fontFamily: "var(--font-cg)",
  fontWeight: 600,
  marginTop: 40,
  fontSize: 16,
  lineHeight: "19px",
  color: "#F3F4F6",
  [theme.breakpoints.down("md")]: {
    width: 220,
    fontSize: 12,
    lineHeight: "13px",
    marginTop: 0,
  },
  [theme.breakpoints.down("sm")]: {
    width: 100,
    fontSize: 11,
  },
}));

export const InfoLine = styled("div")(({ theme }) => ({
  fontFamily: "var(--font-crimson)",
  fontWeight: 400,
  marginTop: 5,
  fontSize: 18,
  lineHeight: "20px",
  color: "#F3F4F6",
  [theme.breakpoints.down("md")]: {
    width: 220,
    marginTop: 6,
    fontSize: 14,
    lineHeight: "100%",
    whiteSpace: "normal",
  },
  [theme.breakpoints.down("sm")]: {
    width: 100,
    marginTop: 6,
    fontSize: 14,
    lineHeight: "100%",
    whiteSpace: "normal",
    color: "#F3F4F6",
  },
}));

export const InfosLine = styled("div")(({ theme }) => ({
  fontFamily: "var(--font-crimson)",
  fontWeight: 400,
  fontSize: 18,
  marginTop: -55,
  color: "#F3F4F6",
  [theme.breakpoints.down("md")]: {
    marginTop: 0,
    "& + &": { marginTop: 6 },
    lineHeight: "16px",
    fontSize: 14,
  },
  [theme.breakpoints.down("sm")]: {
    marginTop: 0,
    "& + &": { marginTop: 6 },
  },
}));

export const FooterCopy = styled("div")(({ theme }) => ({
  position: "absolute",
  left: 60,
  bottom: 20,
  fontFamily: "var(--font-crimson)",
  fontWeight: 400,
  fontSize: 14,
  lineHeight: "24px",
  color: "#FFFFFF",
  opacity: 0.95,
  [theme.breakpoints.between("md", "lg")]: {
    position: "static",
    width: "100%",
    maxWidth: 900,
    margin: "20px auto 30px",
    textAlign: "center",
  },
  [theme.breakpoints.down("md")]: {
    position: "static",
    width: "100%",
    maxWidth: 550,
    margin: "10px 0 0",
    textAlign: "center",
    fontSize: 11,
    lineHeight: "19px",
    marginTop: 20,
    marginBottom: 30,
  },
  [theme.breakpoints.down("sm")]: {
    position: "static",
    width: "100%",
    maxWidth: 375,
    margin: "10px 0 0",
    textAlign: "center",
    fontSize: 10,
    lineHeight: "19px",
    marginTop: 20,
    marginBottom: 30,
  },
}));
